version: '2.12.1'
services:
  mysqldb:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fruits_in_choco
    volumes:
      - db:/var/lib/mysql
  back:
    depends_on:
      - mysqldb
    restart: on-failure
    image: back
    ports:
      - 8080:8080
      - 8983:8983
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8983,server=y,suspend=n
  front:
    image: front
    ports:
      - 3000:3000
volumes:
  db: