export const SET_USERS = 'admin/SET_USERS';
export const PRODUCT_ADDED_SUCCESS = 'admin/PRODUCT_ADDED_SUCCESS';
export const CATEGORY_ADDED_SUCCESS = 'admin/CATEGORY_ADDED_SUCCESS';
export const REVIEW_APPROVED_SUCCESS = 'admin/REVIEW_APPROVED_SUCCESS';
export const SET_REVIEW = 'admin/SET_REVIEW';
export const TOGGLE_IS_FETCHING = 'admin/TOGGLE_IS_FETCHING';
export const SET_PRODUCT = 'admin/SET_PRODUCT';
export const REVIEW_REJECTED_SUCCESS = 'admin/REVIEW_REJECTED_SUCCESS';