export const SET_USERS = 'SET_USERS';
export const PRODUCT_ADDED_SUCCESS = 'PRODUCT_ADDED_SUCCESS';
export const CATEGORY_ADDED_SUCCESS = 'CATEGORY_ADDED_SUCCESS';
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
export const SET_PRODUCT = 'SET_PRODUCT';