export const SET_USERS = 'SET_USERS';
export const PRODUCT_ADDED_SUCCESS = 'PRODUCT_ADDED_SUCCESS';
export const CATEGORY_ADDED_SUCCESS = 'CATEGORY_ADDED_SUCCESS';
export const REVIEW_APPROVED_SUCCESS = 'REVIEW_APPROVED_SUCCESS';
export const SET_REVIEW = 'SET_REVIEW';
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
export const SET_PRODUCT = 'SET_PRODUCT';
export const REVIEW_REJECTED_SUCCESS = 'REVIEW_REJECTED_SUCCESS';