export const INITIALIZED_SUCCESS = 'app/INITIALIZED_SUCCESS';
export const ENQUEUE_SNACKBAR = 'app/ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'app/CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'app/REMOVE_SNACKBAR';
