export const TOGGLE_CART_LAYOUT = 'app/SHOW_CART_LAYOUT';
export const TOGGLE_SIGN_IN_SIGN_UP_POPUP = 'app/SHOW_SIGN_IN_SIGN_UP_POPUP';
export const INITIALIZED_SUCCESS = 'app/INITIALIZED_SUCCESS';
export const ENQUEUE_SNACKBAR = 'app/ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'app/CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'app/REMOVE_SNACKBAR';
