export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REFRESH_TOKEN_SUCCESS =  'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILED =  'REFRESH_TOKEN_FAILED';
