export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'auth/LOGOUT_SUCCESS';
export const REFRESH_TOKEN_SUCCESS =  'auth/REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILED =  'auth/REFRESH_TOKEN_FAILED';
export const TOGGLE_IS_FETCHING = 'auth/TOGGLE_IS_FETCHING';
export const CLEAR_TOKEN = 'auth/CLEAR_TOKEN';
