export const MAKE_ORDER_BEGIN = 'order/MAKE_ORDER_BEGIN';
export const MAKE_ORDER_SUCCESS = 'order/MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_FAILURE = 'order/MAKE_ORDER_FAILURE';
export const FETCH_ORDER_BEGIN = 'order/FETCH_ORDER_BEGIN';
export const FETCH_ORDER_SUCCESS = 'order/FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILURE = 'order/FETCH_ORDER_FAILURE';
export const FETCH_ORDERS_BEGIN = 'order/FETCH_ORDERS_BEGIN';
export const FETCH_ORDERS_SUCCESS = 'order/FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'order/FETCH_ORDERS_FAILURE';
export const UPDATE_ORDER_BEGIN = 'order/UPDATE_ORDER_BEGIN';
export const UPDATE_ORDER_SUCCESS = 'order/UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAILURE = 'order/UPDATE_ORDER_FAILURE';

