export const FETCH_PROFILE_BEGIN = 'profile/FETCH_PROFILE_BEGIN';
export const FETCH_PROFILE_SUCCESS = 'profile/FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'profile/FETCH_PROFILE_FAILURE';
