export const SET_PRODUCTS = 'shop/SET_PRODUCTS';
export const SET_CURRENT_PRODUCT = 'shop/SET_CURRENT_PRODUCT';
export const SET_CURRENT_PRODUCT_REVIEWS = 'shop/SET_CURRENT_PRODUCT_REVIEWS';
export const TOGGLE_IS_FETCHING = 'shop/TOGGLE_IS_FETCHING';
export const SET_FILTERED_TYPES = 'shop/SET_FILTERED_TYPES';
export const ADD_TO_CART = 'shop/ADD_TO_CART';
export const UPDATE_PRODUCT_IN_CART = 'shop/UPDATE_PRODUCT_IN_CART';
export const REMOVE_FROM_CART = 'shop/REMOVE_FROM_CART';
