export const FETCH_USERS_BEGIN = 'user/FETCH_USERS_BEGIN';
export const FETCH_USERS_SUCCESS = 'user/FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'user/FETCH_USERS_FAILURE';
export const FETCH_USER_BEGIN = 'user/FETCH_USER_BEGIN';
export const FETCH_USER_SUCCESS = 'user/FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'user/FETCH_USER_FAILURE';
