spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/marina_cupcake?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

server:
  port: 8080
  servlet:
    context-path: /api/v1

cors:
  allowed-origins: http://localhost:3000

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

jwt:
  expiration: 60000
  expirationRefresh: 86400000
  header: Authorization
  secret: ENC(944RXrWsa3dlg7pFk4CpjA==)
